### PR TITLE
Added Navigation Buttons

### PR DESCRIPTION
**Pull request by Nemesis-AS**
Changes - 

1. Navigation buttons have been added. 
2. The `max-width` of the image/video have been set to `90%` to allow the buttons to be clicked for video
3. The icons have been set to appeared when hovered to provide feedback to user

### CODE REVIEW

**Comment by coppolaemilio** [comment]
I tried the new changes but I don't really like the fact that images can't be 100% of the screen, I use this one more as a presentation kinda mode so not using the 100% of the screen seems like a waste, can you revert that?

**Comment by Nemesis-AS** [comment]
Yeah, I can do that

**Comment by Nemesis-AS** [comment]
The button controls have been added and the image/video can take 100% of the width. And the arrows are still present during hover, just in case

**Comment by coppolaemilio** [comment]
Thank you!

**Pull request merged**
